### PR TITLE
fixed nav bar style

### LINKED ISSUE #9: Fix Navbar style
Problem
--- 
The present navbar does not look like the figma.
- The present navbar:
image
- The navbar we want to make it look like
image

Do this
---
 Refactor the code to fix the problems. In regards to the:
- Font weight 
- Font size
- Font Color
- Background Color of Navbar
- Size of Navbar

Note
---
- Make sure to use the figma properly, you should be able to do this task without guessing anything. All the metadata exists!
- While making your pull request make sure to add in screenshots of what you implemented along with any helpful **notes.**

Links
---
- [How to change css depending on screen size](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)
- [What is Responsive](https://medium.com/@mustwin/responsive-react-9b56d63c4edc)
- [The actual figma to reference](https://www.figma.com/file/i3QlbebnZaaKwrQP2x5qe3/Final-Website-Design?node-id=0%3A1)

### PR DESCRIPTION
**Pull request by adellevo**
* fixed the following: font weight, font size, font color, background color, height
* replaced logo with png of "CS+SG"
* added shadow
* can't figure out how to decrease padding around for the longer width screen 

smallersize
largersize

### CODE REVIEW

**Comment by srirag-vuppala** [comment]
Hi adelle, good work! There's a few things that I've noticed:
1. The CS+SG png isn't located in the images folder, I suspect while you were adding to git you haven't added the image file explicitly.(Since its untracked by git)
2. Also feel free to name it CSSG.png, we can replace it later when we have our new logo. 
3. The navbar seems to be a bit clunky when compared to the figma, is this what you meant by when you couldn't figure out the padding?
- I tried tinkering with the code and it might be the limitation of padding-top and padding-bottom of the logo that causes the entire navbar unable to shrink.
4. Might be the padding but the font size seems slightly small 
5. I think you accidentally added in a `<nav></nav>` in the app.js.

**Comment by adellevo** [comment]
Okay thanks, I'll try to get to those later! 

1, 2, 4, 5) Ooh okay I'll update those.
3) For the padding, I meant the amount of space to the left of the logo and the amount of space to the right of "Contact Us." As for the clunkiness, I did notice that the height depends on the logo image, but I increased the height because the original Figma doc makes it seem too squished? Lol I'll resize the logo to make it more accurate though. Good to know about the padding-top and padding-bottom!

**Comment by srirag-vuppala** [comment]
Hey adelle, I understand what you meant by the padding, I think my solution of adding negative margins worked. I also scaled the font size slightly lower to a 20px(you were right haha!). I also added in a phantom li element so we can get some spacing between the logo and links, try seeing if you can do this in a cleaner way since I'm pretty sure the way I added it isn't good practice. 
If you can't find a better way of doing it I think we should be good for this issue! Thanks and great job!

**Review by srirag-vuppala — APPROVED** [review]
Everything looks great! Thanks!

**Pull request merged**
