### PR TITLE
Officer Card component

### LINKED ISSUE #20: Create Officer Card Component
Problem
---
We need to create a component to display the officer information. 

Do This
---
Create the OfficerCard component that will accept the following properties(props):
- Linkedin link
- Name
- Title
- Image url (of the officer)
- Email

OnClick it should route to the officer's linkedin page. [Should be able to click anywhere on the officer's picture]

image

Naming Convention
---
- The component should be named OfficerCard

Note
---
- Make sure you are naming the components properly and placing them in the appropriate locations within the filesystem. So, the OfficerCard.js is located in the components folder and the OfficerCard.css is located in the assets folder.
- While making your pull request make sure to add in screenshots of what you implemented along with any helpful notes.

Links
---
- [The actual figma to reference](https://www.figma.com/file/i3QlbebnZaaKwrQP2x5qe3/Final-Website-Design?node-id=0%3A1) 
- [Tester profile photo ](https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=934&q=80 )
- [How to change css depending on screen size](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)
- [What is Responsive](https://medium.com/@mustwin/responsive-react-9b56d63c4edc)

### PR DESCRIPTION
**Pull request by anuaparmar**
Installed React bootstrap to utilize the Card component to create the officer card component. The only two issues were finding an optimal way to rescale the image so that it fits within the borders of the card without distorted the image, as well as overlapping the LinkedIn logo on the officer picture.
Officer Card

### CODE REVIEW

**Comment by srirag-vuppala** [comment]
I think you missed the code you've implemented in the commit. I only see the package stuff right now!

**Review by srirag-vuppala — COMMENTED** [review]
Just making sure you saw the comment earlier!

**Comment by anuaparmar** [comment]
My apologies, I did not receive a notification for the first comment, but its uploaded. Thank you!!

**Comment by srirag-vuppala** [comment]
Sorry for the late review! A few things:
- I think you might have forgot to send in props to the actual card. This is important because when we populate the actual officers page with the officer cards we want to send in the name, position, and linkedin link so that it'll be easy to change later on due to the modularity.
- You can look through other components implemented like the "button" one to see how you can implement the props. 
- This video should be helpful as well - https://www.youtube.com/watch?v=8u3mi2ykz18 
- While your at it I think the Officer position needs to be italicized and slightly bigger than the email? Maybe this changed when we changed our font to poppins. 

Let me know if you have any questions :)

**Comment by anuaparmar** [comment]
Added the props, as well as fixed the font size and style for the officer position. Also added space between the position and email as seen in the Figma.

Screenshot:
Officer Card

**Pull request merged**
